## USB port
port: /dev/ttyACM0


##### Calibration ####
### accelerometer
accel_x_min: -261
accel_x_max: 281
accel_y_min: -276
accel_y_max: 276
accel_z_min: -271
accel_z_max: 272
#accel x,y,z (min/max) = -72.51/123.41  -148.32/58.23  -308.84/-197.14

#gyro x,y,z (current/average) = -0.00/-0.00  -0.03/-0.03  0.01/0.01

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.01
gyro_average_offset_y: -0.03
gyro_average_offset_z: 0.00
